name: coursera
channels:
 - conda-forge
 - anaconda
dependencies:
  - nodejs
  - mplleaflet
  - pandas
  - matplotlib
  - ipykernel
  - seaborn
  - pip
  - jupyter
  - pip:
    - tools
    - pycoingecko
    - plotly
    - mplfinance